apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
  namespace: kserve-test
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"

# curl -X POST http://localhost:8080/v1/models/sklearn-iris:predict -H "Content-Type: application/json" -d '{"instances": [[1.2,3.4,2.2,1.3]]}'
